// GENERATED by step8-hw/scripts/gen_regs_h.py -- do not edit.
// Source of truth: step7-host/host/regmap.py, which is itself
// cross-checked against axil_regfile.sv by step7-host/tests/test_regmap.py.
#pragma once

// t2t_axil's register file is mapped into the kernel's control space
// at this offset (see step8-hw/rtl/t2t_kernel.sv).
#define T2T_WINDOW 0x1000u

#define T2T_SYM_BASE       0x0C0u
#define T2T_SYM_STRIDE     16u
#define T2T_SYM_MAX        5u
// symbol k >= 1: +0 locate, +4 band base, +8 stock lo, +12 stock hi
#define T2T_SYM(k) (T2T_SYM_BASE + T2T_SYM_STRIDE * ((k) - 1u))

#define T2T_CTRL           0x0A8u
#define T2T_CTRL_LOAD      0x1u
#define T2T_CTRL_ORDER_ACK 0x2u
#define T2T_CTRL_RESEND    0x4u
#define T2T_RESEND_AGE     0x0ACu
#define T2T_RTO_EN         0x0B0u
#define T2T_RTO_CYCLES     0x0B4u
#define T2T_RTO_RETRIES    0x0B8u
#define T2T_ID             0x1FCu
#define T2T_ID_VALUE       0x54325430u

// config registers: one 32-bit word each, wide fields low word then high
#define CFG_GROUP_IP     0x000u   // 4 byte(s)
#define CFG_UDP_PORT     0x004u   // 2 byte(s)
#define CFG_TRACK_LOCATE     0x008u   // 2 byte(s)
#define CFG_BAND_BASE     0x00Cu   // 4 byte(s)
#define CFG_ENABLE     0x010u   // 1 byte(s)
#define CFG_MAX_SPREAD     0x014u   // 4 byte(s)
#define CFG_RATIO_SHIFT     0x018u   // 1 byte(s)
#define CFG_MIN_QTY     0x01Cu   // 4 byte(s)
#define CFG_ORDER_QTY     0x020u   // 4 byte(s)
#define CFG_POS_LIMIT     0x024u   // 4 byte(s)
#define CFG_MAX_INFLIGHT     0x028u   // 2 byte(s)
#define CFG_SWEEP_EN     0x02Cu   // 1 byte(s)
#define CFG_SWEEP_MIN_LEVELS     0x030u   // 4 byte(s)
#define CFG_SWEEP_GAP_LO  0x034u   // 6 byte(s)
#define CFG_SWEEP_GAP_HI  0x038u   // 6 byte(s)
#define CFG_TOKEN_PREFIX_LO  0x03Cu   // 6 byte(s)
#define CFG_TOKEN_PREFIX_HI  0x040u   // 6 byte(s)
#define CFG_STOCK_LO  0x044u   // 8 byte(s)
#define CFG_STOCK_HI  0x048u   // 8 byte(s)
#define CFG_FIRM     0x04Cu   // 4 byte(s)
#define CFG_TIF     0x050u   // 4 byte(s)
#define CFG_OUCH_MIN_QTY     0x054u   // 4 byte(s)
#define CFG_DISPLAY     0x058u   // 1 byte(s)
#define CFG_CAPACITY     0x05Cu   // 1 byte(s)
#define CFG_SWEEP     0x060u   // 1 byte(s)
#define CFG_CROSS     0x064u   // 1 byte(s)
#define CFG_CUST     0x068u   // 1 byte(s)
#define CFG_DST_MAC_LO  0x06Cu   // 6 byte(s)
#define CFG_DST_MAC_HI  0x070u   // 6 byte(s)
#define CFG_SRC_MAC_LO  0x074u   // 6 byte(s)
#define CFG_SRC_MAC_HI  0x078u   // 6 byte(s)
#define CFG_SRC_IP     0x07Cu   // 4 byte(s)
#define CFG_DST_IP     0x080u   // 4 byte(s)
#define CFG_SRC_PORT     0x084u   // 2 byte(s)
#define CFG_DST_PORT     0x088u   // 2 byte(s)
#define CFG_INIT_SEQ     0x08Cu   // 4 byte(s)
#define CFG_ACK_NUM     0x090u   // 4 byte(s)
#define CFG_WINDOW     0x094u   // 2 byte(s)
#define CFG_INIT_ID     0x098u   // 2 byte(s)
#define CFG_IGMP_EN     0x09Cu   // 1 byte(s)
#define CFG_IGMP_INTERVAL     0x0A0u   // 4 byte(s)
#define CFG_GROUP_IP_B     0x0A4u   // 4 byte(s)

// status counters, read-only
#define ST_RX_DROP           0x100u
#define ST_RX_HWM            0x104u
#define ST_INIT_DONE         0x108u
#define ST_FRAMES_IN         0x10Cu
#define ST_FRAMES_KEPT       0x110u
#define ST_GAP_TOTAL         0x114u
#define ST_OT_OVERFLOW       0x118u
#define ST_PL_OOB            0x11Cu
#define ST_BEAT_DROP         0x120u
#define ST_MSG_DROP          0x124u
#define ST_DELTA_DROP        0x128u
#define ST_SENT              0x12Cu
#define ST_BLK_POS           0x130u
#define ST_BLK_INFLIGHT      0x134u
#define ST_BLK_TXFULL        0x138u
#define ST_POSITION          0x13Cu
#define ST_SEQ_NUM           0x140u
#define ST_FRAME_CNT         0x144u
#define ST_TX_DROP           0x148u
#define ST_BBO_EARLY         0x14Cu
#define ST_BBO_LATE          0x150u
#define ST_BBO_MISMATCH      0x154u
#define ST_RX_PEER_ACK       0x158u
#define ST_RX_OOO            0x15Cu
#define ST_RX_DUP            0x160u
#define ST_RX_SESS_FRAMES    0x164u
#define ST_RTO_FIRED         0x168u
#define ST_RTO_GAVEUP        0x16Cu
#define ST_RB_STORED         0x170u
#define ST_RB_RESENT         0x174u
#define ST_RB_DROP           0x178u
#define ST_BLK_QTY           0x17Cu
#define ST_POSITION_1        0x180u
#define ST_POSITION_2        0x184u
#define ST_POSITION_3        0x188u
#define ST_POSITION_4        0x18Cu
#define ST_BBO_ARB_DROP      0x190u
#define ST_BUILD_GEOM        0x194u
#define ST_ACK_LAST          0x198u
#define ST_ACK_MIN           0x19Cu
#define ST_ACK_MAX           0x1A0u
#define ST_ACK_SAMPLES       0x1A4u
#define ST_ACK_SUM_LO        0x1A8u
#define ST_ACK_SUM_HI        0x1ACu
#define ST_ACK_LOST          0x1B0u

// ---- harness registers, from step8-hw/rtl/t2t_kernel.sv ----
#define K_ID                 0x040u
#define K_CTRL               0x044u
#define K_RP_BASE_LO         0x048u
#define K_RP_BASE_HI         0x04Cu
#define K_RP_BEATS           0x050u
#define K_RP_GAP             0x054u
#define K_CP_BASE_LO         0x058u
#define K_CP_BASE_HI         0x05Cu
#define K_CP_RECS            0x060u
#define K_STATUS             0x064u
#define K_RP_FRAMES          0x068u
#define K_RP_BEATS_OUT       0x06Cu
#define K_CP_FRAMES          0x070u
#define K_CP_BEATS           0x074u
#define K_CP_OVF             0x078u
#define K_CP_STALL           0x07Cu
#define K_L_QUIET            0x080u
#define K_L_MIN              0x084u
#define K_L_MAX              0x088u
#define K_L_LAST             0x08Cu
#define K_L_SUM_LO           0x090u
#define K_L_SUM_HI           0x094u
#define K_L_SAMPLES          0x098u
#define K_L_EXCLUDED         0x09Cu
#define K_L_ORPHANS          0x0A0u
#define K_SP_FRAMES          0x0A4u
#define K_SP_DROP            0x0A8u
#define K_L_HIST             0x0C0u
#define K_M_MIN              0x100u
#define K_M_MAX              0x104u
#define K_M_LAST             0x108u
#define K_M_SUM_LO           0x10Cu
#define K_M_SUM_HI           0x110u
#define K_M_SAMPLES          0x114u
#define K_M_MISSES           0x118u
#define K_M_HIST             0x180u
#define K_C_STATUS           0x200u
#define K_C_TXPKT            0x204u
#define K_C_RXPKT            0x208u
#define K_C_RXERR            0x20Cu
#define K_C_UNF              0x210u
#define K_C_OVFL             0x214u
#define K_C_FLT_P            0x218u
#define K_C_FLT_D            0x21Cu
#define K_C_CAPDROP          0x220u
#define K_C_FEEDHWM          0x224u
#define K_C_ORDHWM           0x228u
#define K_L_NBUCKET          16u
#define K_M_NBUCKET          24u
#define K_ID_VALUE           0x54324B31u   // "T2K1", Phase A
#define K_ID_VALUE_B         0x54324B32u   // "T2K2", Phase B
#define K_C_STATUS_ALIGNED   0x1u
#define K_C_STATUS_LINK_UP   0x2u
#define K_CTRL_START         0x1u
#define K_CTRL_CLEAR_CAPTURE 0x2u
#define K_CTRL_SOFT_RESET    0x4u
#define K_CTRL_CLEAR_LATENCY 0x8u
#define K_STATUS_BUSY        0x1u
#define K_STATUS_DONE        0x2u

// capture record stride, mirrors eth_capture.sv RECORD_BEATS
#define CAPTURE_RECORD_BYTES 2048u
