#!/usr/bin/env python3
"""Emit t2t_regs.h from step7-host/host/regmap.py.

The register map already exists in three places that must agree: the RTL
(axil_regfile.sv localparams), the Python host model (regmap.py), and now a C++
host that talks to the card. step7-host/tests/test_regmap.py keeps the first two
honest by parsing the RTL and diffing. Generating the C header from the same
Python rather than retyping the offsets extends that guarantee to the third: a
mismatch becomes impossible instead of becoming a silent bug where the host
configures the wrong field and the datapath does something inexplicable.

Usage: gen_regs_h.py > host/t2t_regs.h
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "step7-host"))

from host import regmap  # noqa: E402


def cname(name):
    return name.upper().replace("CFG_", "CFG_").replace("ST_", "ST_")


def main():
    out = sys.stdout
    out.write("// GENERATED by step8-hw/scripts/gen_regs_h.py -- do not edit.\n")
    out.write("// Source of truth: step7-host/host/regmap.py, which is itself\n")
    out.write("// cross-checked against axil_regfile.sv by step7-host/tests/test_regmap.py.\n")
    out.write("#pragma once\n\n")

    out.write("// t2t_axil's register file is mapped into the kernel's control space\n")
    out.write("// at this offset (see step8-hw/rtl/t2t_kernel.sv).\n")
    out.write("#define T2T_WINDOW 0x1000u\n\n")

    out.write(f"#define T2T_CTRL           0x{regmap.CTRL_OFFSET:03X}u\n")
    out.write(f"#define T2T_CTRL_LOAD      0x{regmap.CTRL_LOAD:X}u\n")
    out.write(f"#define T2T_CTRL_ORDER_ACK 0x{regmap.CTRL_ORDER_ACK:X}u\n")
    # The resend pulse and its argument. Emitted because a header that stops
    # short of a feature the RTL has is how a feature quietly stays unused.
    out.write(f"#define T2T_CTRL_RESEND    0x{regmap.CTRL_RESEND:X}u\n")
    out.write(f"#define T2T_RESEND_AGE     0x{regmap.RESEND_AGE_OFFSET:03X}u\n")
    out.write(f"#define T2T_ID             0x{regmap.ID_OFFSET:03X}u\n")
    out.write(f"#define T2T_ID_VALUE       0x{regmap.ID_VALUE:08X}u\n\n")

    out.write("// config registers: one 32-bit word each, wide fields low word then high\n")
    for name, width in regmap.REGS:
        offs = regmap.WORD_OFFSET[name]
        for k, off in enumerate(offs):
            suffix = "" if len(offs) == 1 else ("_LO" if k == 0 else "_HI")
            out.write(f"#define {cname(name)}{suffix:<4} 0x{off:03X}u"
                      f"   // {width} byte(s)\n")

    out.write("\n// status counters, read-only\n")
    for name in regmap.STATUS:
        out.write(f"#define {cname(name):<20} 0x{regmap.STATUS_OFFSET[name]:03X}u\n")

    out.write("\n// ---- harness registers, from step8-hw/rtl/t2t_kernel.sv ----\n")
    harness = [
        ("K_ID", 0x040), ("K_CTRL", 0x044),
        ("K_RP_BASE_LO", 0x048), ("K_RP_BASE_HI", 0x04C),
        ("K_RP_BEATS", 0x050), ("K_RP_GAP", 0x054),
        ("K_CP_BASE_LO", 0x058), ("K_CP_BASE_HI", 0x05C),
        ("K_CP_RECS", 0x060), ("K_STATUS", 0x064),
        ("K_RP_FRAMES", 0x068), ("K_RP_BEATS_OUT", 0x06C),
        ("K_CP_FRAMES", 0x070), ("K_CP_BEATS", 0x074),
        ("K_CP_OVF", 0x078), ("K_CP_STALL", 0x07C),
        # latency probe (step8-hw/rtl/lat_probe.sv)
        ("K_L_QUIET", 0x080), ("K_L_MIN", 0x084), ("K_L_MAX", 0x088),
        ("K_L_LAST", 0x08C), ("K_L_SUM_LO", 0x090), ("K_L_SUM_HI", 0x094),
        ("K_L_SAMPLES", 0x098), ("K_L_EXCLUDED", 0x09C), ("K_L_ORPHANS", 0x0A0),
        ("K_L_HIST", 0x0C0),           # 16 consecutive words
        # loaded-latency probe (step8-hw/rtl/lat_loaded.sv), core-clock cycles
        ("K_M_MIN", 0x100), ("K_M_MAX", 0x104), ("K_M_LAST", 0x108),
        ("K_M_SUM_LO", 0x10C), ("K_M_SUM_HI", 0x110),
        ("K_M_SAMPLES", 0x114), ("K_M_MISSES", 0x118),
        ("K_M_HIST", 0x180),           # 24 consecutive words
        # Phase B only (step8-hw/rtl/t2t_kernel_b.sv): the MAC and the paths
        # around it. Reading these on a Phase A bitstream returns 0xDEADBEEF,
        # which is why the host checks the kernel ID before it reads them.
        ("K_C_STATUS", 0x200), ("K_C_TXPKT", 0x204), ("K_C_RXPKT", 0x208),
        ("K_C_RXERR", 0x20C), ("K_C_UNF", 0x210), ("K_C_OVFL", 0x214),
        ("K_C_FLT_P", 0x218), ("K_C_FLT_D", 0x21C), ("K_C_CAPDROP", 0x220),
        ("K_C_FEEDHWM", 0x224), ("K_C_ORDHWM", 0x228),
    ]
    for name, off in harness:
        out.write(f"#define {name:<20} 0x{off:03X}u\n")
    out.write("#define K_L_NBUCKET          16u\n")
    out.write("#define K_M_NBUCKET          24u\n")
    out.write("#define K_ID_VALUE           0x54324B31u   // \"T2K1\", Phase A\n")
    out.write("#define K_ID_VALUE_B         0x54324B32u   // \"T2K2\", Phase B\n")
    out.write("#define K_C_STATUS_ALIGNED   0x1u\n")
    out.write("#define K_C_STATUS_LINK_UP   0x2u\n")
    out.write("#define K_CTRL_START         0x1u\n")
    out.write("#define K_CTRL_CLEAR_CAPTURE 0x2u\n")
    out.write("#define K_CTRL_SOFT_RESET    0x4u\n")
    out.write("#define K_CTRL_CLEAR_LATENCY 0x8u\n")
    out.write("#define K_STATUS_BUSY        0x1u\n")
    out.write("#define K_STATUS_DONE        0x2u\n")
    out.write("\n// capture record stride, mirrors eth_capture.sv RECORD_BEATS\n")
    out.write("#define CAPTURE_RECORD_BYTES 2048u\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
